<a href="https://colab.research.google.com/github/Hey-krrish/Complete-ML-and-DL-from-udemy/blob/main/Data_analysis_with_python_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

In [15]:
import numpy as np

In [ ]:
#simple numpy program
import numpy as np
arr= np.array([1,2,34,43,23,12])
print(arr)

[ 1  2 34 43 23 12]


In [ ]:
#take tuple inside the array function and convert into nd array
import numpy as np
arr=np.array((1,3,6,8,3,))
print(arr)
#print type of the array
print(type(arr))

[1 3 6 8 3]
<class 'numpy.ndarray'>


In [14]:
arr=np.array(42)
print(arr.shape) #print the dimensition.
arr1=np.array([1,2,3,4,5])
print(arr1.shape) ## the output is (5,) that means 5  row 0 column in one dimension
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2.shape) ##(2,5) that means 2 row and 5 column
arr3=np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(arr3.shape) ##(2,2,5) that means 2 x codinate 2 "y" codinate 5 "z" codinate

()
(5,)
(2, 5)
(2, 2, 5)


In [10]:
#checking datatypew of the the array
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)
arr_string=np.array(["apple","banana","mango","coconut"])
print(arr_string.dtype)#u7 means the string element contain maximum 7 unicode element.
arr_string1=np.array(["apple","banana","mango","coconut","pineapple"])
print(arr_string1.dtype) # here maximum length element in the list is pineapple and the no of then word is 9 so print u9
# define data type
arr=np.array([1,2,3,4],dtype="S")
print(arr)
print(arr.dtype)
arr=np.array([1,2,3,4],dtype=np.int64)
print(arr)
print(arr.dtype)
arr=np.array([1,2,3,4],dtype=np.float32)
print(arr)
print(arr.dtype)
print(arr.size)


int64
<U7
<U9
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int64
[1. 2. 3. 4.]
float32
4


In [12]:
# concept of copy and view
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)
# the copy should not be affected by the changes made to the original array
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)
# the view should be affected by the changes made to the original array


[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [13]:
# use of the ndmin
import numpy as np
arr=np.array([1,2,3,4],ndmin=5) # ndmin is create a specific dimensition of the array that we want
print(arr)
print("shape of the array",arr.shape)

[[[[[1 2 3 4]]]]]
shape of the array (1, 1, 1, 1, 4)


In [22]:
# numpy array reshaping.

"""reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension."""
# reshaping from 1D to 2D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)
 #reshaping from 1D to 3D
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr1=arr1.reshape(2,3,2)
print(newarr1)

#reshape with arange function
arr2=np.arange(1,13) #no of element is 12
print(arr2)
newarr2=arr2.reshape(4,3)
print(newarr2)
 # oneline shortcut
arr3=np.arange(1,13).reshape(4,3)
print(arr3,end="\n")


# when use negative index in reshape
arr4=np.arange(1,13).reshape(2,2,-1)
print(arr4)
# when we use the negative index then it donn't affect any shape of the array .
# it automatically reshape it..

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [33]:
 # numpy joining array.
 # joining means putting contents of one or more array in a single array.

 # using concatinate() function
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2)).reshape(2,3)
print(arr)

# using axis
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)
"""axis=0 (default): Concatenation is done along rows (vertically). The arrays are stacked on top of each other.
axis=1: Concatenation is done along columns (horizontally). The arrays are stacked side by side."""

#using stack function.
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1).reshape(2,3) #it is also possible reshape when we use axis
print(arr)
# using hstack()
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)
 # using vstack()

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 4 2]
 [5 3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [38]:
 # ones() and zero() function
arr=np.ones((2,3))
print(arr)
arr1=np.zeros((2,3))
print(arr1)
#linespace()
arr2=np.linspace(0,10,5) # linespace()are devided into similar difference from starting no to ending number
print(arr2)

#identify()
arr3=np.eye(3)
print(arr3)
# also write in this way
arr4=np.identity(3)
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[ 0.   2.5  5.   7.5 10. ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
#stastical function
arr=np.array([1,2,3,4,5])
print(np.mean(arr)) #mean
print(np.median(arr)) #median
print(np.std(arr)) #standard deviation
print(np.var(arr))

3.0
3.0
1.4142135623730951
2.0


In [40]:
#arithmatic operation on array
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [45]:
#logical operation on array
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(np.array_equal(arr1,arr2))
print(np.logical_and(arr1,arr2))
print(np.logical_or(arr1,arr2))
print(np.logical_not(arr1,arr2))

#boolean indexing
arr=np.array([1,2,3,4,5])
x=[True,False,True,False,True]
newarr=arr[x]
print(newarr)

#random.randint()
from numpy import random
x=random.randint(100)
print(x)
#random.rand()
x=random.rand()
print(x)
# find all the number divisiblle by 7 in the array
arr=np.arange(1,100)
newarr=arr[arr%7==0]
print(newarr)
#

False
[ True  True  True  True  True]
[ True  True  True  True  True]
[0 0 0 0 0]
[1 3 5]
0
0.3842093813088685
[ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]
